# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregatePrice_Xts <- function(rdata, period_, numPeriods_, dayStart_, dayEnd_, aggr_vec, pad = TRUE, pad_arg = 0.0) {
    .Call('diveRgence_aggregatePrice_Xts', PACKAGE = 'diveRgence', rdata, period_, numPeriods_, dayStart_, dayEnd_, aggr_vec, pad, pad_arg)
}

#' @export
createXts <- function(values_, stamps_) {
    .Call('diveRgence_createXts', PACKAGE = 'diveRgence', values_, stamps_)
}

#' @export
resizeNV_withAttributes <- function(vec1, vec2) {
    .Call('diveRgence_resizeNV_withAttributes', PACKAGE = 'diveRgence', vec1, vec2)
}

#'@useDynLib diveRgence
#'@export
mcCltInference <- function(rdivDerivX, rdivDerivZ, rdivCont, spotVolPlus, spotVolMinus, nSampl) {
    .Call('diveRgence_mcCltInference', PACKAGE = 'diveRgence', rdivDerivX, rdivDerivZ, rdivCont, spotVolPlus, spotVolMinus, nSampl)
}

kernel_gaussian <- function(cnvData, x0, delta) {
    .Call('diveRgence_kernel_gaussian', PACKAGE = 'diveRgence', cnvData, x0, delta)
}

kernel_epanechnikov <- function(cnvData, x0, delta) {
    .Call('diveRgence_kernel_epanechnikov', PACKAGE = 'diveRgence', cnvData, x0, delta)
}

kernel_indicator <- function(cnvData, x0, delta) {
    .Call('diveRgence_kernel_indicator', PACKAGE = 'diveRgence', cnvData, x0, delta)
}

#' @export
rMPVcpp <- function(rdata, mNum, pPow, yearDays) {
    .Call('diveRgence_rMPVcpp', PACKAGE = 'diveRgence', rdata, mNum, pPow, yearDays)
}

spotVolBaseJump_cpp <- function(spotPoint, rdataSq, rdataAbs, rdataInd, tRange, timeStampYears, avgVol, referenceTime, sepLR, timeDelta, yearLength) {
    .Call('diveRgence_spotVolBaseJump_cpp', PACKAGE = 'diveRgence', spotPoint, rdataSq, rdataAbs, rdataInd, tRange, timeStampYears, avgVol, referenceTime, sepLR, timeDelta, yearLength)
}

